<?php

$generalConfig = [
	'pageList' => [],
	'jwt' => [
		'key' => env('JWT_SECRET'),
		'ttl' => env('JWT_TTL')
	],
	'vivaConnectSmsPushUrl' => env('VIVACONNECT_SMS_PUSH_URL'),
    'valueFirstSmsPushUrl' => env('VALUEFIRST_SMS_PUSH_URL'),
    'vivaConnectSmsUserName' => env('VIVACONNECT_SMS_USER_NAME'),
    'vivaConnectSmsUserPwd' => env('VIVACONNECT_SMS_USER_PWD'),
    'valueFirstSmsUserName' => env('VALUEFIRST_SMS_USER_NAME'),
    'valueFirstSmsUserPwd' => env('VALUEFIRST_SMS_USER_PWD'),
    'valueFirstSmsFrom' => env('VALUEFIRST_FIRST_SMS_FROM'),
	'valueFirstSmsTokenUrl' => env('VALUEFIRST_SMS_TOKEN_URL'),
	'valueFirstVoiceOptUrl' => env('VALUEFIRST_VOICE_OTP_URL'),
	'valueFirstVoiceOptUserName' => env('VALUEFIRST_VOICE_OTP_USER_NAME'),
	'valueFirstVoiceOptPassword' => env('VALUEFIRST_VOICE_OTP_PASSWORD'),
	'vivaConnectSmsSenderId' => env('VIVACONNECT_SMS_SENDERID'),

	/* Voice Otp Config */
	'vfvoiceotpurl' => env('VALUEFIRST_VOICEOTP_URL'),
	'vfvoiceotpcid' => env('VALUEFIRST_VOICEOTP_CID'),
	'vfvoiceotptoken' => env('VALUEFIRST_VOICEOTP_TOKEN'),
	'valueFirstWhatsappUserName' => env('VALUEFIRST_WHATSAPP_USER_NAME'),
	'valueFirstWhatsappUserPwd' => env('VALUEFIRST_WHATSAPP_USER_PWD'),
	'gupShupUserid' =>  env('GUP_SHUP_USER_ID'),
	'gupShupPassword' =>  env('GUP_SHUP_PASSWORD'),
	'fdCalculateUrl' => env('FD_CALCULATOR'),
	'rdCalculateUrl' => env('RD_CALCULATOR'),

	//POSTLOGIN 
	'dummyCpOtp' => env('DUMMY_CP_OTP'),
	"cpOtpExpiry" => env('CP_OTP_EXPIRY'),
	"cpOtpLimit" => env('CP_OTP_LIMIT'),
	'postLoginUrl' => env('POST_LOGIN_URL'),
	'dashboardUrl' => env('DASHBOARD_URL'),
	'fastagUrl' => env('FASTAG_URL'),
	'depositUrl' => env('DEPOSIT_URL'),
	'bankCertStmtUrl' => env('BANK_CERT_STMT_URL'),
	'profileUrl' => env('PROFILE_URL'),
	'fastagdeactUrl' => env('FASTAGDEACT_URL'),
	'paymentUrl' => env('PAYMENT_URL'),
	'paymentcommonUrl' => env('PAYMENTCOMMON_URL'),
	'commonUrl' => env('COMMON_URL'),
	'personimageUrl' => env('PERSONIMAGE_URL'),
	'requeststatusUrl' => env('REQUESTSTATUS_URL'),
	'taxcenterUrl' => env('TAXCENTER_URL'),
	'paymentsearchUrl' => env('PAYMENTSEARCH_URL'),
	'changerequestUrl' => env('MOBILE_NUM_CHANGE_REQUEST_URL'),
	'notificationUrl' => env('NOTIFICATION_URL'),
	'policyUrl' => env('POLICY_URL'),
	'nachsavecancelreqUrl' => env('NACHSAVECANCELREQ_URL'),
	'rtopymntimgUrl' => env('RTOPYMNTIMG_URL'),
	'viewothercompanyinsurUrl' => env('VIEWOTHERCOMPANYINSUR_URL'),
	'gstupdationUrl' => env('GSTUPDATION_URL'),
	'gstupdationvalUrl' => env('GSTUPDATIONVAL_URL'),
	'uploadfiledocUrl' => env('UPLOADFILEDOC_URL'),
	'accesstokenUrl' => env('ACCESSTOKEN_URL'),
	'searchgstUrl' => env('SEARCHGST_URL'),
	'reqarchiveUrl' => env('REQARCHIVE_URL'),
	'depositgeneralurl' => env('DEPOSIT_GENERAL_URL'),
	'depositmaturityurl' => env('DEPOSIT_MATURITY_URL'),
	'contactusLeadpushUrl' => env('CONTACTUS_LEADPUSH'),
	'contactusPincodeUrl' => env('CONTACTUS_PINCODE'),
	'depositNachUrl' => env('DEPOSIT_NACH_URL'),
	'postcustlnurl' => env('POSTCUSTLN_URL'),
	'emipayonlineurl' => env('EMIPAYONLINE_URL'),
	'paytmchecksumurl' => env('PAYTMCHECKSUM_URL'),
	'hsbcpaymentressaveurl' => env('HSBCPAYMENT_RES_SAVE_URL'),
	'soaurl' => env('SOA_URL'),
	'welcomeletterurl' => env('WELCOME_LETTER'),
	'getwelcomeletterurl' => env('GET_WELCOME_LETTER'),
	'purposeurl' => env('PURPOSE_URL'),
	'producturl' => env('PRODUCT_URL'),
	'subproducturl' => env('SUBPRODUCT_URL'),
	'leadsaveurl' => env('LEAD_SAVE_URL'),
	'paymetpropUrl' => env('PAYMENT_RES_PROP_URL'),
	'paymetemiUrl' => env('PAYMENT_EMI_PROP_URL'),
	'complaintRegUrl' => env('COMPLAINT_REGISTRATION'),
	'giCancelPolicyUrl' => env('GI_CANCEL_POLICY_URL'),
	'rapidQBDeposiFetchList'=> env('RAPIDQB_DEPOSIT_FETCHLIST'),
	'rapidQBDepositFetchData'=> env('RAPIDQB_DEPOSIT_FETCH'),
	'depositNew' => env('DEPOSIT_NEW'),
	'cancelpolicy_upload' => env('CANCELPOLICY_UPLOAD'),
	'15ghUrl' => env('15GH_URL'),
	'userDetailsUrl' => env('USER_DETAILS_URL'),
	'fastagSearchUrl' => env('FASTAG_SEARCH_URL'),
	'fastagCustAmtUrl' => env('FASTAG_CUSTAMT_URL'),
	'depositRequestStatus' => env('DEPOSIT_REQUEST_STATUS'),
	'depositGeneral2Url' => env('DEPOSIT_GENERAL2_URL'),
	'depositNotificationUrl' => env('DEPOSIT_NOTIFICATION_URL'),
	'depositRelaseCertificateUrl' => env('DEP_RELCER_URL'),
	'depClosureUrl' => env('DEP_CLOSURE_URL'),
	'fetchverifysetting' => env('FETCHVERIFY_SETTING'),
	'verifyMpinUrl' => env('VERIFY_MPIN_URL'),
	'upfrontChargesUrl' => env('UPFRONT_CHARGES_URL'),
	'customerviewjsonUrl' => env('CUSTOMERVIEWJSON_URL'),
	'userSessionValUrl' => env('USERSESSIONVAL_URL'),
	'loginWithOtpUrl' => env('LOGINWITHOTP_URL'),
	'sflLeadApiUrl' => env('SFL_LEAD_API'),
	'sflWebsiteUrl' => env('SFL_WEBSITE_URL'),
	'sflProductService' => env('SFL_PRODUCT_SERVICE'),
	'sflApi' => env('SFL_API'),

	// Unified Pay EMI
    "unifiedPayEMIUrl" => env('UNIFIED_PAYEMI_API_URL'),
    "unifiedPayEMIAuthUrl" => env('UNIFIED_PAYEMI_AUTH_API_URL'),
    "unifiedPayEMIEncryptKey" => env('UNIFIED_PAYEMI_ENCRYPT_KEY'),
    "unifiedPayEMIEncryptIv" => env('UNIFIED_PAYEMI_ENCRYPT_IV'),
    "unifiedPayEMIDecryptKey" => env('UNIFIED_PAYEMI_DECRYPT_KEY'),
    "unifiedPayEMIDecryptIv" => env('UNIFIED_PAYEMI_DECRYPT_IV'),
    "unifiedPayEMIAesCipher" => env('UNIFIED_PAYEMI_AES_CIPHER'),
	"unifiedPayEMIFetchLoanUrl" => env('UNIFIED_PAYEMI_FETCH_LOAN_API_URL'),
	"unifiedPayEMIFetchPjLoanUrl" => env('UNIFIED_PAYEMI_FETCH_PJLOAN_API_URL'),
	"unifiedPayFetchLoanEMIUrl" => env('UNIFIED_PAYEMI_FETCH_LOAN_EMI_URL'),

	// UPfront Charges 
    "upfrontChargesPropSearchUrl" => env('UPFRONT_CHARGES_PROPSEARCH_API_URL'),
    "upfrontChargesPropPaymentUrl" => env('UPFRONT_CHARGES_PROPPAYMENT_API_URL'),
    "upfrontChargesAuthUrl" => env('UPFRONT_CHARGES_AUTH_API_URL'),

    #NEW VIVACONNECT SMS URL
    "vivaSmsUrl" => env('VIVA_SMS_URL'),
    "vivaSmsUserName" => env('VIVA_SMS_USERNAME'),
    "vivaSmsPassword" => env('VIVA_SMS_PASSWORD'),
	"vivaApiKey" => env('VIVA_API_KEY'),
	"vivaSmsSenderID" => env('VIVA_SMS_SENDERID'),

	#NEW VIVACONNECT SMS URL
	"personalLoanAuthTokenUrl" => env('PERSONAL_LOAN_AUTH_TOKEN_URL'),
	"personalLoanApiUrl" => env('PERSONAL_LOAN_API_URL'),
	"personalLoanDownloadApiUrl" => env('PERSONAL_LOAN_DOWNLOAD_API_URL'),
	"documentAuthTokenUrl" => env('DOCUMENT_AUTH_TOKEN_URL'),

	#DOMAIN_NAME
	"domainName" => env('DOMAIN_NAME'),
	"sitLeadApiUrl"=> env('SIT_LEAD_API'),

	#ADDRESS UPDATE URL
	'depositAddressUpdateUrl' => env('DEPOSIT_ADDRESS_UPDATE_URL')
];

return $generalConfig;